### ISSUE TITLE
Interesting papers

### ISSUE THREAD

**Issue by lassik** [pre-srfi/static-scheme#15]
https://github.com/yallop/effects-bibliography
"A collection of research papers and other resources related to the theory and practice of computational effects."

**Comment by mnieper** [comment]
It is a very good idea to build some (commented and organized) bibliography here. An issue may not be the best fit though. We could easier create a document in the Git repo or use GitHub's Wiki functionality (which is probably the best fit).

**Comment by lassik** [comment]
The wiki is one option, or we could just commit text files into the git repo.

**Comment by mnieper** [comment]
Commenting and organizing text files in the repo is probably harder than to do it in the wiki, I suppose. A community-edited and commented bibliography is so much more valuable than just compiled lists of compiled lists.

**Comment by lassik** [comment]
It's true that the wiki is easier to use but it's more tied to GitHub whereas Git is universal. We could also prepare it in the wiki and commit it into the repo once it's ready.

We should also find a GitHub issues exporter; there are probably several.

**Comment by mnieper** [comment]
Created a simple wiki page with the link above. Therefore closing this issue.
