### ISSUE TITLE
Semi-homogeneous lists

### ISSUE THREAD

**Issue by mnieper** [pre-srfi/static-scheme#17]
By a semi-homogeneous list, I mean a list that is homogeneous (in the type of its elements) apart from finitely many elements (necessarily at the head due to finiteness). Such lists are pervasive in ordinary Scheme, for example as rest argument lists or as the final argument to `apply`. We should explore whether our type system can naturally accomodate such lists. This could also solve the issue of `cons` as `cons` maps a semi-homogeneous list to a semi-homogeneous one.

**Comment by lassik** [comment]
Such a list is naturally represented as a tuple of two lists, a head and a tail, where either or both can be empty. A kind of pair... `(define-type-alias (arg-list 'a) (values (list datum) (list 'a)))` though having all the fixed args as datums is not very convenient.

**Comment by lassik** [comment]
This issue gets at a fundamental tension between dynamic-ness and static-ness in programming languages. Part of the static philosophy is to make things predictable, which means deliberate restrictions. I've actually grown to like this; it clarifies thinking about many problems when you are forced to organize them into well-known types.

It's probably possible to invent a static type system that can express most of what dynamic languages express, but I feel that loses the main point of why have static languages in the first place. As far as I can tell, they started as a formalism that clarifies thought by adding restrictions. The attempt to make them gradually more expressive came later.

**Comment by mnieper** [comment]
> 
> 
> Such a list is naturally represented as a tuple of two lists, a head and a tail, where either or both can be empty. A kind of pair... `(define-type-alias (arg-list 'a) (values (list datum) (list 'a)))` though having all the fixed args as datums is not very convenient.

It is not even correct to have all exceptional list elements as datums because a datum is just some value. Most values aren't datums.

**Comment by mnieper** [comment]
> 
> 
> This issue gets at a fundamental tension between dynamic-ness and static-ness in programming languages. Part of the static philosophy is to make things predictable, which means deliberate restrictions. I've actually grown to like this; it clarifies thinking about many problems when you are forced to organize them into well-known types.
> 
> It's probably possible to invent a static type system that can express most of what dynamic languages express, but I feel that loses the main point of why have static languages in the first place. As far as I can tell, they started as a formalism that clarifies thought by adding restrictions. The attempt to make them gradually more expressive came later.

One can view it from the technical side. A type system has to be expressive and to be sound. By expressiveness, it is meant that all interesting programs are typeable. By soundness, it is meant that the type system makes some guarantees for correctly-typed programs and adheres to these guarantees.

For example, ordinary dynamic Scheme has a trivial type system. This type system is as expressive as it gets because every Scheme program is, trivially, typeable. On the other hand, it is only sound because it does not make any guarantee.

At the other and of the spectrum, there is, say, simply-typed lambda calculus. In this system, I cannot express a lot of programs, but the guarantees it makes are strong: Every well-typed program terminates (for whatever evaluation strategy).

So we are moving in this design space. More expressiveness is always good and if we can represent more general lists than just homogeneous ones all the better. This doesn't mean at all that it makes programs less clear. (Think of dependently-typed languages where the type system is extremely expressive and where the behavior of programs is all so much clearer just by checking and thinking of the types.) The real problem lies in whether we would have to give up guarantees for well-typed programs.

**Comment by lassik** [comment]
> More expressiveness is always good

This is an excellent discussion. We fundamentally disagree on this point and it has far-reaching implications on many central design decisions. I favor all of simplicity, compatibility, a fast compiler, and fast code over expressiveness. There is a level of inexpressiveness that is quite painful (e.g. omitting type variables) but beyond that my standards are not very high :)

**Comment by mnieper** [comment]
> 
> 
> > More expressiveness is always good
> 
> This is an excellent discussion. We fundamentally disagree on this point and it has far-reaching implications on many central design decisions.

Maybe you can explain this in detail in another issue. By your measures, Scheme would be an extremely bad language and C a very good one.

**Comment by aijony** [comment]
Regardless of how expressive the language should be, I'm sure that semi-homogeneous lists will be closer to the 'simple/practical' side of things. Would a list of sum types work?

**Comment by lassik** [comment]
A list of one sum type is expressible as the `(list 'a)` type in most static FP languages. If you mean one list permitting more than one sum type, that's not conventionally as simple since subtyping is not customary in the HM layer.

**Comment by aijony** [comment]
Thinking upon it farther, a sum type may not be the best idea.

**Comment by mnieper** [comment]
I am closing this issue for the moment as it is not quite clear how the type system can accomodate such polymorphic types. Whether we want such a thing also depends on the final shape of a procedure, e.g. whether it allows a variadic number of arguments or not. When this is resolved, we may reopen this issue in case the issue still has to be resolved.
